### ISSUE TITLE
Warning: 1 rules skipped due to selector errors:   50% -> Unmatched selector: %

### ISSUE THREAD

**Issue by NMichas** [qlack/QLACK-Base-Application#2]
![ng_serve_--host_0_0_0_0_--disable-host-check_--proxy-config_proxy_conf_json](https://user-images.githubusercontent.com/2218296/140261209-c292aef3-7810-45c7-aac5-fabd772b0af2.png)

**Comment by mskazi** [comment]
Update browser list to disable support of IE 10 

IE10 is not supporting keyframes
(https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes)
